name: docker-ci

on:
  push:
    branches: [ "feature/save-ingest-history" ]
  pull_request:
    branches: [ "feature/save-ingest-history" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: rag-webapp

    steps:
    # ─── 1. checkout ────────────────────────────────────────────────────────
    - uses: actions/checkout@v4

    # ─── 2. buildx & QEMU (multi-arch) ───────────────────────────────────────
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    # ─── 3. decide where to push ────────────────────────────────────────────
    - name: Compose full image name
      id: img
      run: |
        if [ -z "${{ secrets.REGISTRY_URL }}" ] || [ "${{ secrets.REGISTRY_URL }}" = "docker.io" ]; then
          echo "REGISTRY=docker.io"           >> "$GITHUB_OUTPUT"
          echo "IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}" >> "$GITHUB_OUTPUT"
        else
          echo "REGISTRY=${{ secrets.REGISTRY_URL }}" >> "$GITHUB_OUTPUT"
          echo "IMAGE=${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}"    >> "$GITHUB_OUTPUT"
        fi

    # ─── 4. login to that registry ──────────────────────────────────────────
    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ steps.img.outputs.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # ─── 5. short SHA for deterministic tag ─────────────────────────────────
    - id: vars
      run: echo "SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

    # ─── 6. build & push (uses the IMAGE value picked above) ────────────────
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ steps.img.outputs.IMAGE }}:latest
          ${{ steps.img.outputs.IMAGE }}:${{ steps.vars.outputs.SHA }}
        cache-from: type=registry,ref=${{ steps.img.outputs.IMAGE }}:buildcache
        cache-to:   type=registry,ref=${{ steps.img.outputs.IMAGE }}:buildcache,mode=max
