name: docker-ci

###############################################################################
# When the workflow runs
###############################################################################
on:
  push:
    branches: [ "feature/save-ingest-history" ]   # build only this branch
  pull_request:
    branches: [ "feature/save-ingest-history" ]   # PRs that target the branch

###############################################################################
# Set these once so login + tags always match
###############################################################################
env:
  IMAGE_NAME: rag-webapp           # the repository part on Docker Hub
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}

###############################################################################
# The one and only job
###############################################################################
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # If the repo is public on GH, these are fine.
    # (They’re ignored by Docker Hub but required for GHCR.)
    permissions:
      contents: read
      packages: write

    steps:
    # ──────────── 1) CHECKOUT CODE ───────────────────────────────────────────
    - uses: actions/checkout@v4

    # ──────────── 2) BUILDX & QEMU (for multi-arch) ──────────────────────────
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    # ──────────── 3) LOGIN TO DOCKER HUB ─────────────────────────────────────
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}   # create at https://hub.docker.com/settings/security

    # ──────────── 4) GENERATE TAGS (short SHA + latest) ──────────────────────
    - name: Derive image tags
      id: vars
      run: |
        echo "SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

    # ──────────── 5) BUILD & PUSH ────────────────────────────────────────────
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.SHA }}
        cache-from: type=registry,ref=${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:buildcache
        cache-to:   type=registry,ref=${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
