name: docker-ci

###############################################################################
# 1  WHEN IT RUNS
###############################################################################
on:
  push:
    branches: [ "feature/save-ingest-history" ]
  pull_request:
    branches: [ "feature/save-ingest-history" ]

###############################################################################
# 2  JOB DEFINITION
###############################################################################
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: rag-webapp

    steps:
    # ─────────────────── 1) CHECK OUT SOURCE ────────────────────────────────
    - uses: actions/checkout@v4

    # ─────────────────── 2) BUILD TOOLS (QEMU + Buildx) ─────────────────────
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    # ─────────────────── 3) VERIFY SECRETS EXIST ────────────────────────────
    - name: Verify Docker secrets
      run: |
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ] || [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "::error ::DOCKER_USERNAME or DOCKER_PASSWORD secret is missing."
          exit 1
        fi

    # ─────────────────── 4) LOGIN TO REGISTRY (defaults to Docker Hub) ─────
    - name: Log in to Docker registry
      uses: docker/login-action@v3
      with:
        # If you’re pushing to Docker Hub you can omit "registry".
        # If you set REGISTRY_URL (e.g. "docker.io" or "myregistry.example.com")
        # the same value is used for login and for tags.
        registry: ${{ secrets.REGISTRY_URL || '' }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # ─────────────────── 5) SHORT COMMIT-SHA TAG ────────────────────────────
    - id: vars
      run: echo "SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

    # ─────────────────── 6) BUILD & PUSH ────────────────────────────────────
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/rag-webapp:latest
          ${{ secrets.DOCKER_USERNAME }}/rag-webapp:${{ steps.vars.outputs.SHA }}
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/rag-webapp:buildcache
        cache-to:   type=registry,ref=${{ secrets.DOCKER_USERNAME }}/rag-webapp:buildcache,mode=max
