name: CI – build & unit-tests

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1) source
    - uses: actions/checkout@v4

    # 2) fast unit-tests in the host Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: pytest -q

    # 3) build Docker image (no push) to ensure Dockerfile stays valid
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image (local only)
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true           # image is loaded into the runner
        push: false
        tags: test-img:ci

    # 4) smoke test: does the container start?
    - name: Smoke-check container starts
      run: |
        docker run -d --name app -p 5000:5000 test-img:ci
        sleep 5
        docker ps --filter "name=app" --filter "status=running" | grep app
