name: Build & Push Docker Image

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" \
            | docker login \
              --username "${{ secrets.DOCKER_USERNAME }}" \
              --password-stdin ${{ secrets.REGISTRY_URL }}

      - name: Set safe tag
        id: vars
        run: echo "TAG_NAME=$(echo ${GITHUB_REF##*/} | tr '/' '-')" >> $GITHUB_OUTPUT

      - name: Build & push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ secrets.DOCKER_USERNAME }}/rag-webapp:latest
            ${{ secrets.REGISTRY_URL }}/${{ secrets.DOCKER_USERNAME }}/rag-webapp:${{ steps.vars.outputs.TAG_NAME }}
