name: docker-build-and-test

on:
  push:
    branches: [ "feature/save-ingest-history" ]   # or any branches you like
  pull_request:
    branches: [ "feature/save-ingest-history" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # ─── 1) Get the source code ─────────────────────────────────────────────
    - name: Checkout code
      uses: actions/checkout@v4

    # ─── 2) Set up Buildx (multi-arch builder) ──────────────────────────────
    - uses: docker/setup-buildx-action@v3

    # ─── 3) Build the image, but DO **NOT** push anywhere ───────────────────
    - name: Build local image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true                 # load the image into the runner’s Docker engine
        push: false                # <-- no registry involved
        tags: test-image:ci

    # ─── 4) Run pytest inside the freshly built image ───────────────────────
    - name: Run unit tests
      run: |
        docker run --rm test-image:ci pytest -q
