name: docker-ci                # the workflow’s display name

###############################################################################
# 1. WHEN IT RUNS
###############################################################################
on:
  push:
    branches: [ "feature/save-ingest-history" ]   # build just this branch
  pull_request:
    branches: [ "feature/save-ingest-history" ]   # and PRs targeting it

###############################################################################
# 2. THE JOB
###############################################################################
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Secrets *can* be promoted into a job-level env block.
    # (They are NOT allowed in the top-level env: section.)
    env:
      IMAGE_NAME: rag-webapp
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}   # safe here

    steps:
    # ───────────────────── CHECKOUT CODE ─────────────────────────────────────
    - name: Checkout source
      uses: actions/checkout@v4

    # ───────────────────── BUILD TOOLS ───────────────────────────────────────
    - name: Set up QEMU (multi-arch, optional)
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # ───────────────────── LOGIN TO DOCKER HUB ───────────────────────────────
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}   # ← direct secret reference
        password: ${{ secrets.DOCKERHUB_TOKEN }}      # ← direct secret reference

    # ───────────────────── DERIVE TAGS ───────────────────────────────────────
    - name: Derive image tags
      id: vars
      run: |
        echo "SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

    # ───────────────────── BUILD & PUSH ──────────────────────────────────────
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.SHA }}
        cache-from: type=registry,ref=${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:buildcache
        cache-to:   type=registry,ref=${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
